### ISSUE TITLE
Possible CTD due to mod?

### ISSUE THREAD

**Issue by Moofers** [algernon-A/AdvancedBuildingLevelControl#12]
It'll happen anytime during mainmenu or loading.
[output_log.txt](https://github.com/algernon-A/AdvancedBuildingLevelControl/files/5278913/output_log.txt)

**Comment by algernon-A** [comment]
What troubleshooting steps did you take to identify this mod as the issue?  No issues related to this mod are reported in your log.

BTW, your log shows bunch of problems with your mod collection.  For example, you're simultaneously subscribed to 'Plop the Growables' and 'Disable Zone Check', you're using 'More Beautification' while also subscribed to 'Find It', and a bunch of other stuff.  Regardless of what might or might not be going on with this mod, your mod collection *really* needs an urgent clean-out.

**Comment by Moofers** [comment]
I checked everything until the last known mod to load in the error log. I just assumed it was this mod cause it didn't do until I loaded this mod.

I've cleaned out the disable zone check and more beautification. As I was unaware the mods u mentioned to this now.

**Comment by algernon-A** [comment]
So, in summary:
- You have not performed any systemic troubleshooting steps to narrow down the conflict,
- You have a truly atrocious mod collection that's in dire need of wiping clean and rebuilding from scratch, and
- The log you provided showed no errors from this mod, and a host of lines relating to errors with other mods.

Is that a fair summary?
