### ISSUE TITLE
Please share the 4 dlls currently used in this project(Assembly-CSharp, ColossalManaged, ICities, UnityEngine)

### ISSUE THREAD

**Issue by ninjadev0329** [algernon-A/AdvancedBuildingLevelControl#14]
Hello, algeron!

As I am a C# developer, I'm trying to develop a mod that can control the level of a building now.
When I built this project in VS2017 Community version, I got a Dll(Assembly-CSharp, ColossalManaged, ICities, UnityEngine) reference error.
So I ask you to share the DLLs you are currently using in this project.
I hope a lot of exchanges.
Look forward to hearing from you soon.

Best regards,
Kingwebdev

**Comment by algernon-A** [comment]
Those files are part of the game itself, and I can't share them as they are (obviously) subject to copyright.

It sounds as though you are new to game mod development, particularly Cities Skylines mod development.  A GitHub thread isn't the best place to do that, but instead I recommend starting with [boformer's Cities Skylines modding tutorials on Simtropolis](https://community.simtropolis.com/forums/topic/73404-modding-tutorial-0-your-first-mod/).

Once you're comfortable with the basics, I'm happy to help further; it would be best to get in contact with me either on Steam or one of the Cities Skylines discords (preferred).
