### ISSUE TITLE
I want to contact you

### ISSUE THREAD

**Issue by CJpaekil** [algernon-A/AdvancedBuildingLevelControl#16]
I like Cities Skylines very well
I want to improve this mod a little.
I want to discuss budget and requirements on Skype.
My Skype id is
live:.cid.c02c431544d79ae9
Thanks

**Comment by algernon-A** [comment]
Sorry, I don't do Skype.  GiHub, Discord (find me on most any C:S discord), or Steam Workshop only, please.
