### ISSUE TITLE
(low priority) Abandoned buildings

### ISSUE THREAD

**Issue by originalfoo** [algernon-A/AdvancedBuildingLevelControl#19]
I recently switched from old `No Abandonment` (NA) mod to `ABLC`  mod and ended up with a load of abandoned buildings in the city; that's after enabling the no-abandon settings at main menu and checking they were still enabled after loading city.

This is probably just a minor one-time issue due to switching from NA to ABLC, but thought I'd raise it.

Steps to reproduce:

1. With NA mod enabled, have a city with several buildings that would normally be abandoned (but aren't due to NA mod)
    * Mainly due to lack of workers, low land value, etc
    * I know there's ways to suppress those complaints, but I prefer to keep the complaints showing as a visual reminder that I need to finish implementing that area of the city
2. Exit to desktop
3. Unsub NA, sub ABLC
4. Start game (Launcher > Play)
5. Main menu > CM > Mods:
    * Enable ABLC mod
    * Options > Enable its 'no abandon' features
6. Load city
7. Now several abandoned buildings
8. Check mod settings in-game; `no abandon` features still enabled

The buildings (like all buildings in my city) were plopped via Find It mod

Only way to recover was delete the abandoned buildings (I don't currently have mod tools due to compat issues with EML/PA mods, so I can't just flip the flag to un-abandon those buildings).

Suggestion: Optional "Restore building" button appear on the side-panel (that appears next to selected building world info panel) - when clicked, it clears flags for abandonment & collapsed.

Alternate suggestion: If no-abandon features enabled, check for abandoned buildings on city load and unabandon them.

Alternate alternate suggestion: If user has Natural Disasters DLC subscribed, send out disaster recovery team so user can do the "Rebuild" thing (IRL if an abandoned building collapsed someone would probably go check it out).

Alternate alternate alternate suggestion: A mod (ND DLC required) that sends disaster crews to abandoned buildings, and also power line nodes that were destroyed by lightning, thus giving user option to 'Rebuild' those things; could possibly evolve in to replacement for the abandoned (lol) "Rebuild It!" mod.

**Comment by algernon-A** [comment]
Still having some issues when trying to reproduce.  Do you have an output log or mod listing?

The 'Restore building' button is certainly an idea, ditto auto-unabandonment (which is now totes a proper word).  Not so keen on the Natural Disasters integration ATM, but maybe that's a future idea.

(and there are certain cities in e.g. the US where buildings do collapse and nobody seems to bother, but I understand your point!)

**Comment by originalfoo** [comment]
It seemed to only occur after the transition from `No Abandonment` to `Advanced Building Level Control` mod.

I'm not seeing the issue recur, so it's probably a one off issue and not worth worrying about tbh. Maybe just a note of it on the workshop page would suffice?

That being said, if the side-panel had a button to unabandon a building, that would still be super useful. :)

**Comment by algernon-A** [comment]
Unabandonment implemented in version 1.3.
