### ISSUE TITLE
When downgrading a RICO building using the district control, converts it into a growable.

### ISSUE THREAD

**Issue by Sipke82** [algernon-A/AdvancedBuildingLevelControl#6]
Initial RICO building (level 4):
![image](https://user-images.githubusercontent.com/30873812/86272953-b8b95700-bbcf-11ea-9611-6f2fa180d900.png)

And after clicking force downgrade:
![image](https://user-images.githubusercontent.com/30873812/86272981-c4a51900-bbcf-11ea-90dc-cb11e4732383.png)

**Comment by Sipke82** [comment]
Interestingly it does not happen for this one:
![image](https://user-images.githubusercontent.com/30873812/86273692-f074ce80-bbd0-11ea-9844-433b8747d8c2.png)

Perhaps its related to building size?

**Comment by algernon-A** [comment]
Confirmed, will fix.

**Comment by algernon-A** [comment]
Fixed by 1871d3ebda0966ffd395b7010f4da2f8300f5110
