### ISSUE TITLE
Downgrading a historical growable, converts it to another building

### ISSUE THREAD

**Issue by Sipke82** [algernon-A/AdvancedBuildingLevelControl#7]
Downgrading the following level 4 building:
![image](https://user-images.githubusercontent.com/30873812/86273247-3c734380-bbd0-11ea-8940-5843213878cc.png)

to level 3 results in a different building:
![image](https://user-images.githubusercontent.com/30873812/86273350-688ec480-bbd0-11ea-925f-27bdd93caa25.png)

**Comment by algernon-A** [comment]
Fixed by 47c7b2796121c0ade9349484007c92f264f03129
