### ISSUE TITLE
New buildings should respect district Minimum and maximum setting

### ISSUE THREAD

**Issue by Sipke82** [algernon-A/AdvancedBuildingLevelControl#8]
In my use case i use plop the growables so that all buildings will be historical.

I would set a district to minimum level 2 and maximum level 3. I would like that all buildings i place within that district will be level 2 or 3.
So if i place a level 1 building (which will be historical) should be automatically upgraded to level 2.
So if i place a level 4 building (which will be historical) should be automatically downgraded to level 3.

**Comment by algernon-A** [comment]
Implemented.
